# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2499fada06d4c2ffec5e041aca6c36a831034557e799965f73b7ef38f79b982102c0581e9a20354a01ae5ce8b7adeaf73aec25ad68af08134d1fe46afbe131c

test:
  secret_key_base: 19b046683595fd106b22b932653fee9ffe5a7f529602720f67f3d8c996a4e0b696d3da6e036fd638a2c20be794a5a2abfd099ca8d252aff837ea947cb67cbbbe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
